kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongo
  namespace: pacman
  labels:
    app: mongo
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: mongo
    app.kubernetes.io/name: mongo
    app.kubernetes.io/part-of: pacman-app
    app.openshift.io/runtime: mongodb
    app.openshift.io/runtime-namespace: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        deployment: mongo
    spec:
      volumes:
        - name: mongo-1
          emptyDir: {}
        - name: mongo-2
          emptyDir: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: secret
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongoadmin
          ports:
            - containerPort: 27017
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: mongo-1
              mountPath: /data/configdb
            - name: mongo-2
              mountPath: /data/db
          terminationMessagePolicy: File
          image: ghcr.io/romdalf/mongo:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
